embedding:
  model: "all-MiniLM-L6-v2"

vector_db:
  type: "faiss"
  path: "db/index"

chunking:
  strategy: "fixed"
  size: 512

reranker:
  model: "cross-encoder/ms-marco-MiniLM-L-6-v2"

llm:
  provider: "groq"
  model: "llama-3.3-70b-versatile"

vector_db1:
  type: "qdrant"
  path: "./qdrant_data"